### ISSUE TITLE
Photo direction acqusition

### ISSUE THREAD

**Issue by jreyes13** [SpaceTecPartners/EGNSS4CAP#11]
The photos are generally in the exact location, but the direction of some photos are more than 90º offsets. I calibrated the device compass and I checked compass correctness before shooting, but the direction was saved wrong to the app. 
One example, here I made all 4 photos in a different quarter, but the results…

![image](https://user-images.githubusercontent.com/5262053/114281453-ba595a80-9a3e-11eb-82ad-ccfdf6fec446.png)

**Comment by SpaceTecPartners** [comment]
Unfortunately, it is not a bug. An application logic works correctly. It has been tested on various devices a lot. An azimuth precision is highly dependent on a specific device.
