### ISSUE TITLE
iOS version is nor working properly on dark mode.

### ISSUE THREAD

**Issue by jreyes13** [SpaceTecPartners/EGNSS4CAP#2]
If dark mode is selected the login and the about screens are not readable.

![About_iOS](https://user-images.githubusercontent.com/5262053/114279712-4fa42100-9a36-11eb-923d-84fccabaa57d.jpg)
![Login_iOS](https://user-images.githubusercontent.com/5262053/114279713-503cb780-9a36-11eb-8d55-839058a0d574.jpg)

**Comment by SpaceTecPartners** [comment]
scheduled for fix

**Comment by SpaceTecPartners** [comment]
fixed in release 2.2
