### ISSUE TITLE
The information in the web console is not complete and documented

### ISSUE THREAD

**Issue by jreyes13** [SpaceTecPartners/EGNSS4CAP#21]
If the picture is taken with an iOS device the information is not displayed and the EKF information is empty, without justification.

![image](https://user-images.githubusercontent.com/5262053/114284026-5db16c00-9a4d-11eb-90c1-928ef76e61be.png)

**Comment by SpaceTecPartners** [comment]
The EKF feature is experimental. To avoid a user confusion, it has been removed for now.
