### ISSUE TITLE
The images in the web console have a strange border

### ISSUE THREAD

**Issue by jreyes13** [SpaceTecPartners/EGNSS4CAP#22]
Either is the picture is landscape or portrait, there is a strange border around.

![image](https://user-images.githubusercontent.com/5262053/114284096-c7ca1100-9a4d-11eb-94f0-fdd157ae50dd.png)

![image](https://user-images.githubusercontent.com/5262053/114284111-df08fe80-9a4d-11eb-9ad8-7a110c63b4c1.png)

**Comment by SpaceTecPartners** [comment]
A border has been removed.
