### ISSUE TITLE
No hyperlinks can be created in a task

### ISSUE THREAD

**Issue by jreyes13** [SpaceTecPartners/EGNSS4CAP#4]
In the task definition no hyperlinks can be created and/or text can not be copied. In addition, there are different names between the web console and the Android/iOS version.

![image](https://user-images.githubusercontent.com/5262053/114280813-5f723400-9a3b-11eb-9d02-2ea99c881694.png)
![image](https://user-images.githubusercontent.com/5262053/114280824-6c8f2300-9a3b-11eb-8c53-ef06b3ec3b47.png)
![image](https://user-images.githubusercontent.com/5262053/114280830-731d9a80-9a3b-11eb-9197-87aea0706bfe.png)

**Comment by SpaceTecPartners** [comment]
scheduled for fix

**Comment by SpaceTecPartners** [comment]
A good idea for an improvement. A hyperlink support is added to the task description in rel. 2.2
