### ISSUE TITLE
Screen inactive during the the path tracking

### ISSUE THREAD

**Issue by jreyes13** [SpaceTecPartners/EGNSS4CAP#5]
When tracking a path, the screen becomes inactive and the tracking is stopped (Android and iOS version).

![image](https://user-images.githubusercontent.com/5262053/114281595-7b77d480-9a3f-11eb-8b75-407ee61ec22d.png)

**Comment by SpaceTecPartners** [comment]
scheduled for further investigation and replication of the bug

**Comment by SpaceTecPartners** [comment]
fixed in rel 2.2
