### ISSUE TITLE
Methodology of area measurement does not support the operations in the way the PAs

### ISSUE THREAD

**Issue by jreyes13** [SpaceTecPartners/EGNSS4CAP#8]
The methodology of area measurement does not support the operations in the way the PA operators are used to apply during the standard OTSC (following the DG JRC guidelines and users needs). 
a. The app. does not have the possibility to opt between the continuous versus vertex method.
b. The app. uses the continuous measurement mode (frequency ???), but so many points are captured, which has a negative impact on the measurement itself. The point network is too dense. The frequency of the points is too high, and cannot be set up by the operator (or set up from pre-default options – e.g. every 3rd second, every 5th second…). Hence, if you remain in a certain place for just a few seconds, the app. makes a cluster of points that affect the path tracking and area measurement. 
c. There is no possibility to change the measurement method during the measurement – to change the vertex versus the continuous method depending on the situation on the field. 
d. There is no possibility to delete the last measured point/s (manually point by a point directly during the measurement.) Hence, if an outlier point is captured during the measurement, the operator sees it, however, he/she cannot do anything about that during the measurement. Leading either to re-doing the entire measurement or to correct the measurement in the post-processing. However, the tool shall support the operations that way, that the post-processing is minimised.
![image](https://user-images.githubusercontent.com/5262053/114281169-20dd7900-9a3d-11eb-9697-e246a1877004.png)
e. Due to the very high density of points the shape of fields (the border points) are unclear and the shapes of fields are arched instead of a clear delineation of the polygon boundaries. 
f. There is no check or warning on crossing geometries during the path tracking. This might lead to improper polygon delineation.
![image](https://user-images.githubusercontent.com/5262053/114281190-45395580-9a3d-11eb-89c7-f6d69bf0bc98.png)

**Comment by SpaceTecPartners** [comment]
continuous mode
- frequency setting introduced - range 1-60s

vertex mode
- introduced a vertex mode
- convex hull calculation of coordinates is possible, standard coordinates taken from the Location Service is possible
- UI modifications on a map view to enable new mode
